apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
spec:
  selector:
    app: nextjs
  ports:
    - protocol: TCP
      port: 80 # 외부에서 접근할 포트
      targetPort: 3000 # 컨테이너 내부 포트
  type: NodePort # Minikube 환경에서 외부 노출을 위해 NodePort 타입 사용